In [6]:
import pandas as pd
import numpy as np
from tabulate import tabulate

df = pd.read_csv('Census_Enrichment.csv')  #Pretty simple, just reads and prints out the enrichment file obtained from the census

df = df.head()

print(df)

      County Name State  Estimate Total population  \
0   United States   NaN                  326569308
1         Alabama   NaN                    4893186
2  Autauga County    AL                      55639
3  Baldwin County    AL                     218289
4  Barbour County    AL                      25026

   Estimate Total population Under 5 years  \
0                                 19650192
1                                   293932
2                                     3235
3                                    11960
4                                     1332

   Estimate Total population 5 to 9 years  \
0                                19979039
1                                  294776
2                                    3725
3                                   11559
4                                    1550

   Estimate Total population 10 to 14 years  \
0                                  21107910
1                                    315204
2                                      3645
3                                     15171
4                                      1429

   Estimate Total population 15 to 19 years  \
0                                  21174955
1                                    321308
2                                      3716
3                                     13005
4                                      1386

   Estimate Total population 20 to 24 years  \
0                                  21820378
1                                    323960
2                                      3458
3                                     11031
4                                      1532

   Estimate Total population 25 to 29 years  \
0                                  23262155
1                                    334650
2                                      3659
3                                     12284
4                                      1846

   Estimate Total population 30 to 34 years  ...  \
0                                  22223010  ...
1                                    307217  ...
2                                      3419  ...
3                                     12103  ...
4                                      1797  ...

   Estimate!!Percent Female!!Total population Under 18 years  \
0                                               21.6
1                                               21.2
2                                               22.3
3                                               20.6
4                                               22.2

   Estimate!!Percent Female!!Total population 18 to 24 years  \
0                                                9.0
1                                                9.0
2                                                8.2
3                                                6.9
4                                                7.1

   Estimate!!Percent Female!!Total population 15 to 44 years  \
0                                               38.7
1                                               37.7
2                                               39.0
3                                               33.6
4                                               33.4

   Estimate!!Percent Female!!Total population 16 years and over  \
0                                               80.8
1                                               81.3
2                                               81.0
3                                               82.0
4                                               80.8

   Estimate!!Percent Female!!Total population 18 years and over  \
0                                               78.4
1                                               78.8
2                                               77.7
3                                               79.4
4                                               77.8

   Estimate!!Percent Female!!Total population 21 years and over  \
0                                               74.5
1                                               74.8
2                                               74.7
3                                               76.3
4                                               74.9

   Estimate!!Percent Female!!Total population 60 years and over  \
0                                               23.9
1                                               25.2
2                                               22.5
3                                               29.3
4                                               29.7

   Estimate!!Percent Female!!Total population 62 years and over  \
0                                               21.3
1                                               22.4
2                                               19.6
3                                               26.0
4                                               26.6

   Estimate!!Percent Female!!Total population 65 years and over  \
0                                               17.6
1                                               18.5
2                                               16.8
3                                               21.5
4                                               22.8

   Estimate!!Percent Female!!Total population 75 years and over
0                                                7.7
1                                                8.0
2                                                7.2
3                                                8.7
4                                                9.7

[5 rows x 195 columns]

In [48]:
#Each student member creates notebooks to read the Enrichment data and displays them on a notebook.

In [8]:
df = pd.read_csv('Census_Enrichment.csv')
covid = pd.read_csv('super_covid_data.csv') 

#df = df.head()
#covid = covid.head()

merged = pd.merge(df, covid, on=['County Name', 'State'], how='left')  #This merges the two files on the State column

merged.head()
print(merged)


merged.to_csv('covidandreducedcencus.csv')  #This converts the merged dataframe into a new csv

            County Name State  Estimate Total population  \
0         United States   NaN                  326569308
1               Alabama   NaN                    4893186
2        Autauga County    AL                      55639
3        Baldwin County    AL                     218289
4        Barbour County    AL                      25026
...                 ...   ...                        ...
3190  Sweetwater County    WY                      43352
3191       Teton County    WY                      23356
3192       Uinta County    WY                      20374
3193    Washakie County    WY                       7933
3194      Weston County    WY                       6942

      Estimate Total population Under 5 years  \
0                                    19650192
1                                      293932
2                                        3235
3                                       11960
4                                        1332
...                                       ...
3190                                     2870
3191                                     1046
3192                                     1464
3193                                      442
3194                                      344

      Estimate Total population 5 to 9 years  \
0                                   19979039
1                                     294776
2                                       3725
3                                      11559
4                                       1550
...                                      ...
3190                                    3655
3191                                    1192
3192                                    1607
3193                                     428
3194                                     551

      Estimate Total population 10 to 14 years  \
0                                     21107910
1                                       315204
2                                         3645
3                                        15171
4                                         1429
...                                        ...
3190                                      2940
3191                                      1418
3192                                      1833
3193                                       589
3194                                       232

      Estimate Total population 15 to 19 years  \
0                                     21174955
1                                       321308
2                                         3716
3                                        13005
4                                         1386
...                                        ...
3190                                      3039
3191                                       933
3192                                      1303
3193                                       538
3194                                       477

      Estimate Total population 20 to 24 years  \
0                                     21820378
1                                       323960
2                                         3458
3                                        11031
4                                         1532
...                                        ...
3190                                      2612
3191                                       985
3192                                      1074
3193                                       421
3194                                       405

      Estimate Total population 25 to 29 years  \
0                                     23262155
1                                       334650
2                                         3659
3                                        12284
4                                         1846
...                                        ...
3190                                      2740
3191                                      2104
3192                                      1169
3193                                       324
3194                                       353

      Estimate Total population 30 to 34 years  ...  2023-07-15_deaths  \
0                                     22223010  ...                NaN
1                                       307217  ...                NaN
2                                         3419  ...              235.0
3                                        12103  ...              731.0
4                                         1797  ...              104.0
...                                        ...  ...                ...
3190                                      3134  ...              142.0
3191                                      2209  ...               16.0
3192                                      1352  ...               43.0
3193                                       432  ...               51.0
3194                                       446  ...               24.0

      2023-07-16_deaths  2023-07-17_deaths  2023-07-18_deaths  \
0                   NaN                NaN                NaN
1                   NaN                NaN                NaN
2                 235.0              235.0              235.0
3                 731.0              731.0              731.0
4                 104.0              104.0              104.0
...                 ...                ...                ...
3190              142.0              142.0              142.0
3191               16.0               16.0               16.0
3192               43.0               43.0               43.0
3193               51.0               51.0               51.0
3194               24.0               24.0               24.0

      2023-07-19_deaths  2023-07-20_deaths  2023-07-21_deaths  \
0                   NaN                NaN                NaN
1                   NaN                NaN                NaN
2                 235.0              235.0              235.0
3                 731.0              731.0              731.0
4                 104.0              104.0              104.0
...                 ...                ...                ...
3190              142.0              142.0              142.0
3191               16.0               16.0               16.0
3192               43.0               43.0               43.0
3193               51.0               51.0               51.0
3194               24.0               24.0               24.0

      2023-07-22_deaths  2023-07-23_deaths  population
0                   NaN                NaN         NaN
1                   NaN                NaN         NaN
2                 235.0              235.0     55869.0
3                 731.0              731.0    223234.0
4                 104.0              104.0     24686.0
...                 ...                ...         ...
3190              142.0              142.0     42343.0
3191               16.0               16.0     23464.0
3192               43.0               43.0     20226.0
3193               51.0               51.0      7805.0
3194               24.0               24.0      6927.0

[3195 rows x 2728 columns]

In [50]:
#Each student member performs initial merges with the COVID-19 data using the variables in the Enrichment data.